MR-666 Cypress test for floor switching
arubanetworks/meridian-web-sdk pull request #209
Opened 2020-10-09 00:41 UTC by vercasson

- [ ] This change is documented in CHANGELOG.md

2020-10-09 01:03 UTC, wavebeem requested changes
I think this PR warrants some discussion about the appropriate use of CSS classes within the Web SDK, and what we want to officially support.

As-is, this adds a ton of surface area and risk to the Web SDK, and doesn't even document any of the new features.

2020-10-09 01:03 UTC, wavebeem commented on src/Overlay.js
> +};
I think you should put the `cx` call outside of this css function. That's how we do it everywhere else, and it would make it easier to keep track of where we're adding our public CSS classes.

Speaking of that, is this something we're prepared to support for theming? I noticed both the left and right overlays have the same `meridian-map-overlay` class, and it's not exactly clear to me that we do want to expose these things.

I remember when we worked on the Web SDK, we agreed to keep the "overlays" as sort of a "black box" of customization since there are _so many_ things to customize within it, and we want to reserve the ability to make some drastic changes inside there without breaking compatibility.

Which is another reason why I've been pushing for folks to replace the info popup on click if they want things to look/feel different.

2020-10-09 01:03 UTC, wavebeem commented on src/Overlay.js
> +};
Same comment as cssOverlayLeft

2020-10-09 01:03 UTC, wavebeem commented on src/Overlay.js
> +  <button className={cx("close", cssClose)} onClick={onClick}>
It's not good for us to add unprefixed CSS classes inside the Web SDK. Someone's site could easily have a CSS class called `close` that clashes with our styles and makes things look funky. I think this should at least be `meridian-close`, but I'd point back to my earlier comment about "should this even be a public CSS thing".

2020-10-09 01:03 UTC, wavebeem commented on src/OverlaySearchBar.js
> +          className={cx("search", cssSearchInput)}
Same comment about unprefixed classes being added.

2020-10-09 16:38 UTC, vercasson commented
@wavebeem Thanks for the comments, I'll respond after my appt. Good questions.

2020-10-09 18:49 UTC, vercasson commented
@wavebeem @tarakreft 
As for test targeting I would really-really like to only target `data-testid`s . I'd be happy to fix that as part of this. The sooner the better if we decide to do this. 

I'd like to keep this PR open and discuss on Monday. I need to finish my annual review.

2020-10-09 18:59 UTC, wavebeem commented
>  As for test targeting I would really-really like to only target `data-testid`s . I'd be happy to fix that as part of this. The sooner the better if we decide to do this.

That'd be perfect! I think something like `data-testid="meridian--private--search"` would be good to make it extra clear these are just automation hooks for testing, not official API.

2020-10-12 20:24 UTC, vercasson commented on src/FloorOverlay.js
>                    )}
I purposely repeated `meridian--private--` below to make the strings more searchable.

2020-10-12 21:43 UTC, wavebeem approved these changes
looks great! thanks for making those changes

2020-10-12 21:43 UTC, wavebeem commented on src/FloorOverlay.js
>                    )}
good call!

2020-10-12 21:45 UTC, merged