[WIP] Draft of Custom Element
arubanetworks/meridian-web-sdk pull request #217
Opened 2020-11-25 00:39 UTC by wavebeem

- [ ] This change is documented in CHANGELOG.md

2020-11-25 22:38 UTC, wavebeem commented on src/web-sdk.tsx
> +export class MeridianMapElement extends HTMLElement {
This class is the real "meat" of this PR. Everything else is basically just test updates to use the new syntax and stuff.

2020-11-25 23:11 UTC, tarakreft approved these changes

2020-12-01 00:20 UTC, vercasson requested changes
Let's discuss during our meeting.

2020-12-01 00:20 UTC, vercasson commented on src/web-sdk.tsx
> +export class MeridianMapElement extends HTMLElement {
I don't think we should go this route, this seems really half-baked and adds another layer of logic and complexity to deal with. One example:  If you simply add the custom element with the minimum requirements nothing happens as you still need to call `updateMap'. And some properties can be specified on the custom element, but not others. ...

Why don't we just use a MutationObserver? They are well supported now. 
https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

2020-12-01 16:03 UTC, wavebeem reviewed
I still think a custom element could actually be a good developer experience, but I agree with Anthony that we should use MutationObserver instead. I'm gonna close this PR and rewrite the ticket.

https://codepen.io/wavebeem/pen/zYBXgap?editors=0011

^ I have a proof-of-concept about using MutationObserver to do the same concept and it seems to work well.

2020-12-01 16:03 UTC, wavebeem commented on src/web-sdk.tsx
> +export class MeridianMapElement extends HTMLElement {
Ah, I always forget about MutationObserver. Half-baked seems a little harsh, but yeah I knew that this could stand to be improved a bit with respect to error handling in the no-attrs case, as well as unifying attrs/props. Custom elements are a lot of work by hand, haha.

2020-12-01 16:03 UTC, closed without merging

2020-12-01 17:40 UTC, vercasson commented on src/web-sdk.tsx
> +export class MeridianMapElement extends HTMLElement {
Par-baked is what I meant! ;) I do see value in this exploration and a future for this approach.

2020-12-01 17:48 UTC, vercasson commented
> I still think a custom element could actually be a good developer experience, but I agree with Anthony that we should use MutationObserver instead. I'm gonna close this PR and rewrite the ticket.
> 
> https://codepen.io/wavebeem/pen/zYBXgap?editors=0011
> 
> ^ I have a proof-of-concept about using MutationObserver to do the same concept and it seems to work well.

One thing I noticed when playing with MutationObservers is that I needed to observe something inside the map target element or the parent. Simply observing the target element didn't trigger an observation event when I blew away the element. You'll most likely run into this 🤷‍♂️