MR-1146 d3 zoom event fix
arubanetworks/meridian-web-sdk pull request #255
Opened 2021-04-05 23:02 UTC by vercasson

- [ ] This change is documented in CHANGELOG.md

2021-04-05 23:04 UTC, vercasson commented
@wavebeem Any thoughts on how the changelog zoom related note should read?

2021-04-05 23:43 UTC, wavebeem commented
> 
> 
> @wavebeem Any thoughts on how the changelog zoom related note should read?

I couldn't reproduce this in production. I don't think we ever released this bug. So it shouldn't be mentioned in the changelog.

2021-04-05 23:45 UTC, wavebeem requested changes

2021-04-05 23:45 UTC, wavebeem commented on src/MapComponent.tsx
>              ? this.props.shouldMapPanZoom(d3Event)
This changes the type of `shouldMapPanZoom`, but you ignored the difference by using `any` in the definition of `restrictedPanZoom`. I think you should update the type in `web-sdk.tsx` to match whatever the type of `d3Event` is here

2021-04-05 23:49 UTC, vercasson commented on src/MapComponent.tsx
>              ? this.props.shouldMapPanZoom(d3Event)
The type here for the event is `any` as specified by d3-zoom. They used `any` and made a comment on why.

2021-04-07 18:05 UTC, wavebeem approved these changes

2021-04-07 18:53 UTC, merged